// Multi-day itinerary containing schedule slots
import 'package:explore_index/features/trip_planner/data/models/schedule_slot.dart';

class Itinerary {
  final String id;
  final String title;
  final String countryId;
  final String countryName;
  final String countryFlag;
  final List<String> cityIds;
  final DateTime startDate;
  final DateTime endDate;
  final List<ScheduleSlot> slots;
  final bool isAutoGenerated;

  const Itinerary({
    required this.id,
    required this.title,
    required this.countryId,
    required this.countryName,
    required this.countryFlag,
    required this.cityIds,
    required this.startDate,
    required this.endDate,
    required this.slots,
    required this.isAutoGenerated,
  });

  int get totalDays => endDate.difference(startDate).inDays + 1;

  List<DateTime> get days => List.generate(
        totalDays,
        (i) => DateTime(startDate.year, startDate.month, startDate.day + i),
      );

  List<ScheduleSlot> slotsForDay(DateTime day) {
    return slots
        .where((s) =>
            s.date.year == day.year &&
            s.date.month == day.month &&
            s.date.day == day.day)
        .toList()
      ..sort((a, b) => a.startMinutes.compareTo(b.startMinutes));
  }

  int get totalPlaces => slots.map((s) => s.placeId).toSet().length;

  Itinerary copyWith({
    String? id,
    String? title,
    String? countryId,
    String? countryName,
    String? countryFlag,
    List<String>? cityIds,
    DateTime? startDate,
    DateTime? endDate,
    List<ScheduleSlot>? slots,
    bool? isAutoGenerated,
  }) =>
      Itinerary(
        id: id ?? this.id,
        title: title ?? this.title,
        countryId: countryId ?? this.countryId,
        countryName: countryName ?? this.countryName,
        countryFlag: countryFlag ?? this.countryFlag,
        cityIds: cityIds ?? this.cityIds,
        startDate: startDate ?? this.startDate,
        endDate: endDate ?? this.endDate,
        slots: slots ?? this.slots,
        isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      );
}
